name: client
on: workflow_call
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - run: |
        pip install --upgrade pip
        pip install \
        --trusted-host dp-hackathon-2023.s3-website-us-east-1.amazonaws.com \
        -i http://dp-hackathon-2023.s3-website-us-east-1.amazonaws.com/simple \
        helloworld
        python -c 'import helloworld; helloworld.hello()'
