name: client
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python --version
          python -m pip install --upgrade pip setuptools
